### ISSUE TITLE
Update six dependency version

### ISSUE THREAD

**Issue by pointyointment** [svisser/ipuz#1]
pip downgraded my six when I installed ipuz. [six changelog](https://allmychanges.com/p/python/six/)

**Comment by svisser** [comment]
Hello, thanks for letting me know. I have removed the version number in `setup.py` and there is now a new version of the package (`0.1.4`). This means you can specify yourself what version of `six` you need. Based on the `six` changelog this seems a safe thing to do but let me know if you encounter any issues.

**Comment by svisser** [comment]
Please check it here: https://pypi.python.org/pypi/ipuz/0.1.4
